### ISSUE TITLE
CSS "load" order inconsistency between on-the-fly/dev mode and (sfx)bundle mode.

### ISSUE THREAD

**Issue by andreasgrimm** [systemjs/plugin-css#18] opened 2015-03-13 10:15 UTC
using the non-bundling, on-the-fly transpilation mode, changing the order of explicit CSS import statements, changes the load order accordingly (which can be observed in DevTools' Network tab). For instance

```javascript
import 'bootstrap/css/bootstrap.css!css';
import 'bootstrap/css/bootstrap-theme.css!css';
import 'angular-xeditable/dist/css/xeditable.css!css';
```

loads/applies `xeditable.css` after the bootstrap CSS was loaded and applied, whereas

```javascript
import 'angular-xeditable/dist/css/xeditable.css!css';
import 'bootstrap/css/bootstrap.css!css';
import 'bootstrap/css/bootstrap-theme.css!css';
```

would do it vice versa.

But as soon as you bundle, you can't rely on that order anymore.

For all the CSS you have control over, you of course would not need to rely on CSS load order but rather implement your CSS overrides by applying CSS specificity.
But it's a different use case when you want to use a vendor lib that relies on CSS load order to override CSS from another vendor lib (instead of using CSS specificity).

**Comment by guybedford** [comment] 2015-03-13 10:18
Sure - yes we should aim to ensure the order is maintained in bundling.

**Comment by AdamBurgess** [comment] 2015-03-13 10:42
In my tests even the on-the-fly transpilation doesn't work in order.
Take this example: if the main file you import looks like this:

```
import './1.css!'
import './styles2'
import './3.css!'
```

and styles2.js is `import './2.css!'`

I see the order in the HTML is 1, 3, 2. (and not 1, 2, 3)

**Comment by AdamBurgess** [comment] 2015-03-13 11:32
I can't seem to reproduce this (I'm using the source from my fork, though)
The bundle's `loads` array is always in the same order as the import order.

**Comment by andreasgrimm** [comment] 2015-03-13 11:43
In `app.css` I override e.g. the `font-family`

**Comment by AdamBurgess** [comment] 2015-03-13 11:57
What browser are you using (for on-the-fly)? I'm using chrome 43. Both on-the-fly and bundling work as expected. I'm using my fork here, but I don't get them out-of-order with the current plugin either.
```javascript
import 'angular-material/angular-material.css!AdamBurgess/plugin-css';
import 'app.css!AdamBurgess/plugin-css';
```

where my app.css contains
```css
button, select, html, textarea, input {
    font-family: "Custom Font Here";
}
```

the output build.css looks something like:
```css
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.8.3
 */*,:after,:before{box-sizing:border-box} ..... lots of css ..... button,html,input,select,textarea{font-family:"Custom Font Here"}
```
in my fork, since clean-css is used to merge the css, the `original button,html,input,select,textarea` `font-family` declaration is removed completely (deduplicated)

**Comment by andreasgrimm** [comment] 2015-03-13 12:10
Hold on, that might actually not be true. To be more specific (and give you a potential reproduction scenario), you might want to take a look in https://github.com/ng-next/ng-next-example where in main.js I have ...

```javascript
import 'angular-material/angular-material.css!css';
// ...
import 'app.css!css';
```

Now during bundling (gulp task `bundle`) I generate 2 bundles, `app.js` (own code) and `lib.js` (3rd party dependencies) this way:

```bash
Building the bundle tree for text + css + ... + angular-material...
ok   Built into lib.js, unminified.

Building the bundle tree for main - text - css - angular - ... - angular-material...
ok   Built into app.js, unminified.
```

But in `app.js` there's still the CSS from `angular-material.css` included (which in addition doesn't adhere to import order in `main.js`, which you can test if you change the import order of the two CSS import statements) which should probably not be the case.

This might in addition raise the question, if then the load order of the individual bundles does (and if it should) affect the probably intended load order specified by the order of the import statements.

**Comment by AdamBurgess** [comment] 2015-03-13 12:36
>But in app.js there's still the CSS from angular-material.css included

I did a `gulp serve-build` and I don't see any angular-material.css source inside of app.js...I do see it inside lib.js....and in the HEAD the angular css is loaded before the app css, too.

but as you say, if you change the order to `app.css!` then `angular-material.css!`, the material css is still loaded first, which is incorrect

**Comment by andreasgrimm** [comment] 2015-03-13 12:38
@AdamBurgess ok, thank you for correcting me and clarifying this issue :)

**Comment by AdamBurgess** [comment] 2015-03-13 12:42
I don't think this is a bug in plugin-css though: main.js code must run after all imported libraries have been initialised. If you include angular-material in one file (lib.js) and app.css in another (app.js), the only specification is that angular-material and app.css must be injected before main.js's main code is ran.

Since you break up your builds into two files, whichever file is included first will load the css. Test it: change the built index.html to include app.js and then lib.js. The custom app.css will be injected first.

**Comment by AdamBurgess** [comment] 2015-03-13 12:59
Actually, I take that back. If instead of injecting the CSS directly, what about making each css depend on the previous css file, and injecting the css inside that module? That would make them always import in order. I'll see if I can mock something up.

**Comment by andreasgrimm** [comment] 2015-03-13 13:18
I currently don't have a reproduction, but during my tests it seemed that regarding CSS load/application order relying on CSS being a (jspm) dependency of a package, made it even worse.

But you are obviously not talking about jspm deps but only SystemJS CSS PlugIn on top of pure ES6 imports. But hmm, even if it works it sounds like that would complicate things (unnecessarily).

**Comment by andreasgrimm** [comment] 2015-03-13 13:46
As for importing (ES6) JavaScript modules the load order of `app.js` and `lib.js` is irrelevant, I'd intuitively assume that for importing other types like CSS (or TXT, JSON etc.) it should be irrelevant as well.

**Comment by AdamBurgess** [comment] 2015-03-13 14:06
>it should be irrelevant as well.

That was my assumption too. What exactly is this issue about, then? I'm lost.

Also, note that `angular-material` (which you import) imports `./angular-material.css!` for you.
You don't actually need to import it manually. I can't seem to get both angular-material and app.css in the app.js build file (you said 'But in app.js there's still the CSS from angular-material.css included').

>what about making each css depend on the previous css file

after testing it seems this isn't possible, as the plugin only gets passed the css files that will actually be used in the bundle (which makes sense...)

>if you change the order to app.css! then angular-material.css!, the material css is still loaded first.

I think I tested this wrong - angular-material.css in angular-material was using systemjs/plugin-css but app.css and angular.material in main.js was using my fork (d'oh, my bad, forget everything I've said)

**Comment by andreasgrimm** [comment] 2015-03-13 14:10
regarding your example with the `font-family` being set in `app.css`. When you change the order of the imports to

```javascript
import 'app.css!AdamBurgess/plugin-css';
import 'angular-material/angular-material.css!AdamBurgess/plugin-css';
```

... then on the page you should see the `font-family` from `angular-material.css`, right? At least in my above mentioned example project, when I do this, then I only see the angular-material font-family in on-the-fly mode whereas when (sfx)bundling, I'm still getting the font-family from the app.css.

**Comment by andreasgrimm** [comment] 2015-03-13 14:13
> 'But in app.js there's still the CSS from angular-material.css included'
That was a false statement. This is not the case.

**Comment by AdamBurgess** [comment] 2015-03-13 14:40
ah, yes, now I see, and can correctly reproduce.

I touched on it above, but I think all it is is your use of two output files and because angular-material imports the css file for you. Systemjs will ignore the `angular-material.css` import in your main file generation, as it's been included in `angular-material` (which has been ignored).

So you unfortunately only have one option: one output file containing everything.

**Closed** 2015-04-19 21:31 UTC
